name: Build and Push Docker Image

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine tags
      id: tags
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "tags=pr-${{ github.event.number }},pr-${{ github.event.number }}-${{ github.sha }}" >> $GITHUB_OUTPUT
        else
          # Branch name (replace slashes with dashes)
          BRANCH_TAG=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          # Short SHA
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          # Full SHA
          FULL_SHA="${{ github.sha }}"
          
          echo "tags=$BRANCH_TAG,$BRANCH_TAG-$SHORT_SHA,$BRANCH_TAG-$FULL_SHA" >> $GITHUB_OUTPUT
          echo "branch_tag=$BRANCH_TAG" >> $GITHUB_OUTPUT
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "full_sha=$FULL_SHA" >> $GITHUB_OUTPUT
        fi

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.tags.outputs.tags }},${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Output image info
      if: github.event_name != 'pull_request'
      run: |
        echo "Built and pushed image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        echo "Custom tags: ${{ steps.tags.outputs.tags }}"
        echo "Metadata tags: ${{ steps.meta.outputs.tags }}"
        echo "Branch: ${{ steps.tags.outputs.branch_tag }}"
        echo "Short SHA: ${{ steps.tags.outputs.short_sha }}"
        echo "Full SHA: ${{ steps.tags.outputs.full_sha }}" 